# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 258a2efd0fb11da57c415ccf94baad7b70a59d8e5f8e44251dce31047c342359d471ed4a92b905424c651391250dfab1d4498a2abcb409542a5685464f2ecc80

test:
  secret_key_base: 9e3ec015cb46c73c0ac4393aab83d141eefd6d5864d967775c98843db5f70ba90d582a6b046e86fdb998ce41847fbb00b6592b8ef6f07cfda2d04c6aeb54b1d4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
